on:
  push:
    branches:
      - main
    paths:
      - README.md
      - cyblog-meta
      - cyblog-footer.html
      - Makefile
  workflow_dispatch:

jobs:
  resume:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v3
      - name: "Setup Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: "build"
        run: |
          sudo apt-get install -fy make chromium-browser
          git clone https://github.com/xyzshantaram/cyblog cyblog-repo
          cd cyblog-repo
          make compile
          cp cyblog ..
          cd ..
          rm -rf cyblog-repo
          export PATH="$PATH:$(pwd)"
          make dist
        continue-on-error: false
      - name: "commit changes"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Built PDF and HTML page."
          git push origin main
